### ISSUE TITLE
Unresolved local references in Parameters should be warnings, not errors when validating

### ISSUE THREAD

**Issue by lmckenzi** [hapifhir/org.hl7.fhir.core#289] opened 2020-08-01 16:14 UTC
In the text on Parameters, it says that "resolution stops at parameter.resource".  However, it also says that "the applicable Operation Definition may specify how references may be resolved between parameters".  Thus, even though the validator isn't expected to successfully resolve the references, it's legal to have such references, so long as the Operation indicates how resolution should take place.  Right now, the validator is treating unresolved errors as unsuppressable errors.  These should be warnings instead so that, on review that the references are legal according to the Operation, they can be suppressed.  

(In the long term, it should be possible to tie an example to a particular operation as input or output and validate according to parameter.referencedFrom, but there's no ability to tie examples to an Operation input or output right now.)

**Comment by lmckenzi** [comment] 2020-08-01 16:14
Note - for an example of this issue, see https://build.fhir.org/ig/HL7/davinci-ehrx/qa.html

**Comment by grahamegrieve** [comment] 2020-08-02 22:06
The problem is that Patient/1 is not resolved in the IG as a whole.

**Comment by lmckenzi** [comment] 2020-08-02 22:49
Why does it need to if it resolves within the Parameters?  What's the mechanism to have a parameter in one resource point to a resource in a different parameter where the operation says that's what's supposed to happen?

**Comment by grahamegrieve** [comment] 2020-08-03 02:16
Fixed - references resolve in Parameters resource now. Agree about long term, but that should be a different task

**Closed by grahamegrieve** 2020-08-03 02:16 UTC
Labels: bug, validation-core
