### ISSUE TITLE
Validator not comparing profiles

### ISSUE THREAD

**Issue by rcon1012** [hapifhir/org.hl7.fhir.core#613] opened 2021-10-04 14:59 UTC
Using the latest release of the validator at the time of this issue being posted, no output is generated.

I've used several commands, but[ the command on the confluence page](https://confluence.hl7.org/pages/viewpage.action?pageId=35718580#UsingtheFHIRValidator-ComparingProfiles) is a prime example of nothing happening.

Here is my exact command (will have to change -dest obviously):
java -jar validator_cli.jar -compare -dest C:\Users\conleyrg\Documents -version 4.0 -ig hl7.fhir.us.carin-bb#1.1.0 -ig hl7.fhir.us.davinci-crd#1.0.0 -left http://hl7.org/fhir/us/carin-bb/StructureDefinition/C4BB-Patient -right http://hl7.org/fhir/us/davinci-crd/StructureDefinition/profile-patient

Here is the output:
PS C:\Users\conleyrg\OneDrive - UPMC\Desktop\FHIR Tests> java -jar validator_cli.jar -compare -dest C:\Users\conleyrg\Documents -version 4.0 -ig hl7.fhir.us.carin-bb#1.1.0 -ig hl7.fhir.us.davinci-crd#1.0.0 -left http://hl7.org/fhir/us/carin-bb/StructureDefinition/C4BB-Patient -right http://hl7.org/fhir/us/davinci-crd/StructureDefinition/profile-patient
FHIR Validation tool Version 5.5.4 (Git# 6aaf495c85ae). Built 2021-09-29T17:51:47.529Z (4 days old)
  Java:   1.8.0_131 from C:\Program Files\Java\jre1.8.0_131 on amd64 (64bit). 3591MB available
Valid destination directory provided: "C:\Users\conleyrg\Documents")
  Paths:  Current = C:\Users\conleyrg\OneDrive - UPMC\Desktop\FHIR Tests, Package Cache = C:\Users\conleyrg\.fhir\packages
  Params: -compare -dest C:\Users\conleyrg\Documents -version 4.0 -ig hl7.fhir.us.carin-bb#1.1.0 -ig hl7.fhir.us.davinci-crd#1.0.0 -left http://hl7.org/fhir/us/carin-bb/StructureDefinition/C4BB-Patient -right http://hl7.org/fhir/us/davinci-crd/StructureDefinition/profile-patient
  Load FHIR v4.0 from hl7.fhir.r4.core#4.0.1 - 4575 resources (00:05.0606)
  Load hl7.terminology#2.1.0 - 3767 resources (00:01.0858)
  Terminology server http://tx.fhir.org - Version 1.9.389 (00:01.0946)
  Load hl7.fhir.us.core#3.1.1 - 145 resources (00:00.0093)
  Load hl7.fhir.us.carin-bb#1.1.0 - 95 resources (00:00.0014)
  Load hl7.fhir.us.core#3.1.0 - 143 resources (00:00.0083)
  Load hl7.fhir.us.davinci-hrex#0.2.0 - 17 resources (00:00.0002)
Installing hl7.fhir.uv.sdc#current to the package cache
  Fetching:...
  Installing: ... done.
  Load hl7.fhir.uv.sdc#current - 113 resources (00:02.0588)
  Load hl7.fhir.us.davinci-crd#1.0.0 - 31 resources (00:00.0011)
  Get set...  go (00:01.0524)

Nothing is created in the destination folder (which does exist prior to running the command). Several colleagues were able to recreate this issue.

**Comment by grahamegrieve** [comment] 2021-12-01 06:34
I think this is fixed now - please confirm

**Comment by OliverCardoza** [comment] 2021-12-01 15:44
I can confirm that the comparison is performed and an HTML site is generated in the output directory. I'm not calibrated enough to understand if the comparison is correct but I'll trust that it is and file separate bug if I find otherwise.

Even though the output data was generated I did get a console error. I think it's caused because the tool is hard-coded to expect a desktop/UI system and I was running within an SSH terminal.

Error:
```
Exception in thread "main" java.awt.HeadlessException:                                                                                                                                                             
No X11 DISPLAY variable was set, but this program performed an operation which requires it.                                                                                                                        
        at java.desktop/java.awt.Desktop.getDesktop(Desktop.java:301)                                                                                                                                              
        at org.hl7.fhir.validation.cli.services.ComparisonService.compareStructureDefinitions(ComparisonService.java:74)                                                                                           
        at org.hl7.fhir.validation.cli.services.ComparisonService.doLeftRightComparison(ComparisonService.java:38)                                                                                                 
        at org.hl7.fhir.validation.ValidatorCli.doLeftRightComparison(ValidatorCli.java:227)                                                                                                                       
        at org.hl7.fhir.validation.ValidatorCli.main(ValidatorCli.java:160)
```

Root cause: 

https://github.com/hapifhir/org.hl7.fhir.core/blob/13073a189d938520a78abff38f8707000a54f2c3/org.hl7.fhir.validation/src/main/java/org/hl7/fhir/validation/cli/services/ComparisonService.java#L74

If you'd like I can file a separate bug for that. Thanks for the fix!

**Closed** 2022-05-31 14:22 UTC
Labels: wontfix, check-fixed
