### ISSUE TITLE
Option locale without effect

### ISSUE THREAD

**Issue by mmreith** [hapifhir/org.hl7.fhir.core#408] opened 2020-12-23 08:09 UTC
The option locale has no function

-locale en

does not change the output

**Comment by grahamegrieve** [comment] 2021-02-07 22:16
what language did you try?

**Comment by mmreith** [comment] 2021-02-08 06:20
just english (en). Language is set to german by default through windows command, but i need the display in english for debugging purposes.

**Comment by markiantorno** [comment] 2021-08-11 20:05
I'm assuming this is regarding the output of the validator cli @mmreith ?

**Comment by mmreith** [comment] 2021-08-12 07:15
@markiantorno correct. Do you need more information?

**Comment by markiantorno** [comment] 2021-08-16 17:44
@mmreith can you send me the exact steps to reproduce please?

Thank you.

**Comment by mmreith** [comment] 2021-08-18 04:56
@markiantorno My call was, but you could use whatever you like: java -jar validator_cli.jar -ig aws-zertifizierung\Sollprofile\PF20_all_Mussfelder -ig aws-zertifizierung\Sollprofile\PF24 -ig aws-zertifizierung\Sollprofile\PF22_24_Mussfelder -ig KBV_FHIR_AW\KBV-Basis -ig KBV_FHIR_AW\Terminologie -ig KBV_FHIR_AW\Application -ig KBV_FHIR_AW\Extensions-KOPIE -ig de.basisprofil.r4#0.9.11 -version 4.0.1 -recurse -no-extensible-binding-warnings **-locale en** Mustermann_Martina_5faa0942-a96c-43c7-ad25-0854829bd083_AW.xml

but i did not get an output in english. If you want to reproduce that, you might have to set **-locale de**, since this is an available translation,

**Comment by mmreith** [comment] 2022-02-10 07:49
@markiantorno do you need more information?

**Comment by DarthGizka** [comment] 2022-05-27 15:11
I'm having the same problem and now I find that it has already been reported here.

F7 confirms that the parameter gets parsed correctly and that `CliContext.locale` (which defaults to English anyway) gets set accordingly. Couldn't find where the translation occurs because it doesn't happen when I run the jar under the IntelliJ debugger (had `-locale nl` in order to make it differ from both the system locale and defaultish locales like C or en).

One problem definitely lies in `CliContext::setLocale(Locale)`, which receives a valid Locale object but stores only its localised display language name. In `CliContext::getLocale()` there is a half-hearted attempt at getting a Locale object for this stored string, but that must fail because a localised display language name is not a valid BCP 47 language tag as expected by [`Locale.forLanguageTag(String)`](https://docs.oracle.com/javase/8/docs/api/java/util/Locale.html#forLanguageTag-java.lang.String-).

Replacing [`locale.getDisplayLanguage()`](https://docs.oracle.com/javase/8/docs/api/java/util/Locale.html#getDisplayLanguage--) with [`locale.toLanguageTag()`](https://docs.oracle.com/javase/8/docs/api/java/util/Locale.html#toLanguageTag--) in `CliContext::setLocale(Locale)` should fix that particular problem. However, whether this solves the problem with the `-locale` parameter remains to be seen. I am in no position to build the validator jar, so I cannot test this.

**Comment by mmreith** [comment] 2022-11-22 12:13
That feature would still be nice

**Comment by dotasek** [comment] 2022-11-24 14:40
Fixed in https://github.com/hapifhir/org.hl7.fhir.core/pull/1002

**Closed by dotasek** 2022-11-24 14:40 UTC
Labels: i18n
