### ISSUE TITLE
can't build successful. for 5.6.79

### ISSUE THREAD

**Issue by linxd** [hapifhir/org.hl7.fhir.core#997] opened 2022-11-21 15:19 UTC
In centos, jdk-11 or jdk-1.8 , all got this.   for network wall?
----------- 
[INFO] Total time: 7:57.942s
[INFO] Finished at: Mon Nov 21 23:13:37 CST 2022
[INFO] Final Memory: 28M/644M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:buildnumber-maven-plugin:1.4:create-metadata (downstream) on project org.hl7.fhir.utilities: Execution downstream of goal org.codehaus.mojo:buildnumber-maven-plugin:1.4:create-metadata failed. NullPointerException -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :org.hl7.fhir.utilities

**Comment by jamesagnew** [comment] 2022-11-21 16:28
Duplicate of #996

**Closed by jamesagnew** 2022-11-21 16:28 UTC
