### ISSUE TITLE
Error converting MedicationRequest from R4 to R3

### ISSUE THREAD

**Issue by roguelider** [hapifhir/org.hl7.fhir.core#456] opened 2021-03-11 22:03 UTC
I'm trying to convert a MedicationRequest resource from R4 to R3 using the structure map provided in http://hl7.org/fhir/medicationrequest-version-maps.html but I'm getting the following error:

Exception in thread "main" org.hl7.fhir.exceptions.FHIRException: Unable to find map(s) for http://hl7.org/fhir/StructureMap/*4to3
	at org.hl7.fhir.r4.utils.StructureMapUtilities.resolveGroupReference(StructureMapUtilities.java:1669)
	at org.hl7.fhir.r4.utils.StructureMapUtilities.executeGroup(StructureMapUtilities.java:1398)
	at org.hl7.fhir.r4.utils.StructureMapUtilities.transform(StructureMapUtilities.java:1377)
	at com.tibco.bw.fhir.transformoperation.TransformOperation.transformOperation(TransformOperation.java:46)
	at com.tibco.bw.fhir.transformoperation.TransformOperation.main(TransformOperation.java:26)

According to https://www.hl7.org/fhir/r3maps.html the map has been tested and should be completely functional. Is there a specific place where this file should be placed? Also, where can it be found?

**Comment by markiantorno** [comment] 2021-05-03 18:14
I just test the following code, and it works on the latest master:

```java
    org.hl7.fhir.r4.model.MedicationRequest mr = new org.hl7.fhir.r4.model.MedicationRequest();
    Resource resource = VersionConvertor_30_40.convertResource(mr, false);
    System.out.println(resource);
```

Please provide an example, including:
1. All inputs and commands as they exist locally on your machine.
2. The expected output.
3. The actual output.

I'll close this issue for now, and mark as not a bug. Once you add the required information, we can investigate further.

**Closed by markiantorno** 2021-05-03 18:14 UTC
